### ISSUE TITLE
3. Explore & discuss the effects of wing aspect ratio vs wing efficiency.

### ISSUE THREAD

**Issue by samiamandyesican** [samiamandyesican/497R#13]
- Questions

**Comment by samiamandyesican** [comment]
I have a couple of ideas, but I'm not sure the best direction to go with calculating wing efficiency.

**Comment by samiamandyesican** [comment]
@Cardoza2 Is there another way to extract the lift/drag from the coefficients produced by VortexLattice since I don't know what $\rho$ or $V_{\infty}$ are?

**Comment by Cardoza2** [comment]
Without $V_\infty$ or $\rho$, it is impossible to get the actual lift and drag from the coefficients. Look at the [definition of the lift coefficient](https://en.wikipedia.org/wiki/Lift_coefficient). It is defined with the freestream velocity and the density. 

Taking a look at the docs for `VortexLattice`, Vinf appears to be the freestream velocity, which the user defines... so you should have that.

The density is a little more difficult. I had to look inside the source code to see what was going on. They were dimensionalizing by a constant `RHO`, which they define on the main file (VortexLattice.jl). 
```julia
# value for dimensionalizing, included just for clarity in the algorithms
const RHO = 1.0
```

In my opinion they should just have it be an optional argument, then they can define it to be whatever they want... but yeah. The code is using 1.0.

**Comment by samiamandyesican** [comment]
This step has been completed.
